import Navbar from '../components/Navbar'
import Head from 'next/head'
import HomeHero from '@/components/HomeHero'
import Footer from '../components/Footer'
import HomeMain from '@/components/HomeMain'
import HomeAsaid from '@/components/HomeAsaid'
import Contact from '@/components/Contact'

export default function App() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <HomeHero />
        <HomeMain />
        <HomeAsaid />
        <Contact />
        <Footer />
      </div>
    </>
  )
}
